Make syslog config check more permissive
pivotal-cf/cf-rabbitmq-test-release pull request #1
Opened 2022-10-18 14:13 UTC by ablease

## Why is do we need this?
This is to prevent failures in the event that a change in stemcell causes filesystem changes. The moved to new stemcells seems to have introduced a filesystem change for the deafult installation location for the rsyslogd modules.

Originally we were checking that the rsyslog configuration contained this substring 

`loading module '/usr/lib/rsyslog/imfile.so'`

In the new stemcell the rsyslogd conig shows that the imfile.so location is

`0432.047353666:main thread    : modules.c: loading module '/usr/lib/x86_64-linux-gnu/rsyslog/imfile.so'`

This commit changes the check, so that we are only looking for `imfile.so'` in the rsyslogd config. This should prevent failures if the location changes again in a future stemcell change.

2022-10-18 14:47 UTC, coro requested changes

2022-10-18 14:47 UTC, coro commented on jobs/syslog-configuration-test/templates/post-deploy.sh
> +  [[ $RSYSLOG_CONFIG_CHECK = *"imfile.so'"* ]] ||
Could we still check that the message contains 'loading module'? I'm worried we'd miss for e.g. file not found errors.

2022-10-18 15:47 UTC, ablease commented on jobs/syslog-configuration-test/templates/post-deploy.sh
> +  [[ $RSYSLOG_CONFIG_CHECK = *"imfile.so'"* ]] ||
Agreed. I updated the branch with a new commit, which performs a regex check on the output of the rsyslog config

2022-10-19 08:39 UTC, MirahImage approved these changes

2022-10-19 08:50 UTC, merged